# Задачи с сайта sql-ex.ru

In [21]:
# !wget https://sql-ex.ru/download/sql-ex-pg.sql

# utf-8-sig - разновидность UTF-8, автоматически удаляющая BOM (Byte Order Mark) из начала файла.
with open("sql-ex-pg.sql", "r", encoding="utf-8-sig") as file:
    sql = file.read()

In [22]:
import pandas as pd
from sqlalchemy import create_engine, text

engine = create_engine("postgresql+psycopg2://postgres:root@localhost:5432/psql_db")

# SQLAlchemy в режиме engine.connect() работает внутри транзакции, которая не коммитится автоматически, если не использовать begin().
with engine.begin() as con:  # Решение: engine.begin() - транзакция автокоммитятся
    for i, statement in enumerate(sql.split(";")):
        stmt = statement.strip()
        if stmt:
            con.execute(text(stmt))

In [23]:
def select(sql):
    with engine.connect() as con:
        return pd.read_sql(sql, con)

## Краткая информация о базе данных "Компьютерная фирма"

Схема БД состоит из четырех таблиц:
Product(maker, model, type)
PC(code, model, speed, ram, hd, cd, price)
Laptop(code, model, speed, ram, hd, price, screen)
Printer(code, model, color, type, price)
Таблица Product представляет производителя (maker), номер модели (model) и тип ('PC' - ПК, 'Laptop' - ПК-блокнот или 'Printer' - принтер). Предполагается, что номера моделей в таблице Product уникальны для всех производителей и типов продуктов. В таблице PC для каждого ПК, однозначно определяемого уникальным кодом – code, указаны модель – model (внешний ключ к таблице Product), скорость - speed (процессора в мегагерцах), объем памяти - ram (в мегабайтах), размер диска - hd (в гигабайтах), скорость считывающего устройства - cd (например, '4x') и цена - price (в долларах). Таблица Laptop аналогична таблице РС за исключением того, что вместо скорости CD содержит размер экрана -screen (в дюймах). В таблице Printer для каждой модели принтера указывается, является ли он цветным - color ('y', если цветной), тип принтера - type (лазерный – 'Laser', струйный – 'Jet' или матричный – 'Matrix') и цена - price.

### Задание 1

Найдите номер модели, скорость и размер жесткого диска для всех ПК стоимостью менее 500 дол. Вывести: model, speed и hd

In [24]:
sql = """--sql
select
    pc.model,
    pc.speed,
    pc.hd
from
    pc
where
    price < 500
order by
    pc.model,
    pc.speed,
    pc.hd"""
select(sql)

  model  speed    hd
0  1232    450   8.0
1  1232    450  10.0
2  1232    500  10.0
3  1260    500  10.0

### Задание 2

Найдите производителей принтеров. Вывести: maker

In [25]:
sql = """--sql
select distinct
    p.maker
from
    product p
where
    type like 'Printer'"""
select(sql)

  maker
0     A
1     D
2     E

### Задание 3

Найдите номер модели, объем памяти и размеры экранов ПК-блокнотов, цена которых превышает 1000 дол.

In [26]:
sql = """--sql
select
    l.model,
    l.ram,
    l.screen
from
    laptop l
where
    l.price > 1000
order by
    l.model,
    l.ram,
    l.screen"""
select(sql)

  model  ram  screen
0  1298   64      15
1  1750  128      14
2  1752  128      14

### Задание 4

Найдите все записи таблицы Printer для цветных принтеров.

In [27]:
sql = """--sql
select
    p.*
from
    printer p
where
    color = 'y'"""
select(sql)

   code model color type  price
0     2  1433     y  Jet  270.0
1     3  1434     y  Jet  290.0

### Задание 5

Найдите номер модели, скорость и размер жесткого диска ПК, имеющих 12x или 24x CD и цену менее 600 дол.

In [28]:
sql = """--sql
select
    pc.model,
    pc.speed,
    pc.hd
from
    pc
where
    pc.cd in ('12x', '24x')
    and pc.price < 600
order by
    pc.model,
    pc.speed,
    pc.hd"""
select(sql)

  model  speed    hd
0  1232    450   8.0
1  1232    450  10.0
2  1232    500  10.0
3  1260    500  10.0

### Задание 6

Для каждого производителя, выпускающего ПК-блокноты c объёмом жесткого диска не менее 10 Гбайт, найти скорости таких ПК-блокнотов. Вывод: производитель, скорость.

In [29]:
sql = """--sql
select
    p.maker,
    l.speed
from
    product p
    left join laptop l on p.model = l.model
where
    l.hd >= 10.0
order by
    p.maker,
    l.speed"""
select(sql)

  maker  speed
0     A    450
1     A    600
2     A    750
3     B    750

### Задание 7

Найдите номера моделей и цены всех имеющихся в продаже продуктов (любого типа) производителя B (латинская буква).

In [30]:
sql = """--sql
with
    all_products as (
        select
            pc.model,
            pc.price
        from
            pc
        union
        select
            l.model,
            l.price
        from
            laptop l
        union
        select
            pr.model,
            pr.price
        from
            printer pr
    )
select
    ap.*
from
    all_products ap
where
    ap.model in (
        select
            p.model
        from
            product p
        where
            p.maker = 'B'
    )"""
select(sql)

  model   price
0  1121   850.0
1  1750  1200.0